# Cloud Build configuration for automated deployments
# This file is used by Google Cloud Build to build and deploy the app

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/spildspotter-app:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/spildspotter-app:latest'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/spildspotter-app:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/spildspotter-app:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'spildspotter-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/spildspotter-app:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GCP_PROJECT_NAME=$PROJECT_ID,GCP_PROJECT_LOCATION=europe-west1'

# Store the built images
images:
  - 'gcr.io/$PROJECT_ID/spildspotter-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/spildspotter-app:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'
